name: Post Merge Checks

on:
  push:
    branches:
      - master

jobs:
    
  build-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.8.1'
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Builds
      run: node_modules/.bin/nx run-many --configuration production --parallel 4 --targets build-package
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts/
        path: artifacts/

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.8.1'
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Linting
      run: node_modules/.bin/nx run-many --parallel 4 --targets lint

  release-dry-run:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.8.1'
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Release Dry Run
      run: node_modules/.bin/nx release --dry-run
    
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.8.1'
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Unit Tests
      run: node_modules/.bin/nx run-many --parallel 4 --targets unit-test
