name: Post Merge Checks

on:
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Linting
      run: node_modules/.bin/nx run-many --parallel 4 --targets lint
    
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Unit Tests
      run: node_modules/.bin/nx run-many --parallel 4 --targets unit-test
    
  build-library:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Builds
      run: node_modules/.bin/nx run-many --configuration production --parallel 4 --targets build-library
