name: Post Merge Checks

on:
  push:
    branches:
      - master

jobs:
  prerequisites:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install
    - name: Run Unit Tests
      run: node_modules/.bin/nx run-many --parallel 4 --targets unit-test