name: Version & Release

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.8.1'
    - name: Install Dependencies
      run: yarn install --immutable
    - env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Run Versioning
      run: node_modules/.bin/nx version
