name: Version & Release

on:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.8.1'
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Run Builds
      run: node_modules/.bin/nx run-many --configuration production --parallel 4 --targets build-package
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifact/

  release:
    if: github.ref_name == github.event.repository.default_branch
    needs: build-package
    permissions:
      contents: write
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.8.1'
        registry-url: https://registry.npmjs.org/
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: artifact/
    - name: Install Dependencies
      run: yarn install --immutable
    - name: Configure Git
      run: |
        git config --global user.email "rich.kielty@gmail.com"
        git config --global user.name "Richard Kielty"
    - env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.PUBLISH_WORKFLOW_TOKEN }}
      name: Run Release
      run: node_modules/.bin/nx release --skip-publish --verbose
      shell: bash
